/** ATLAS TIME — الإعدادات: تحكم محلي واضح باللغة ونظام الساعة والسمة دون أثر على هندسة الساعة. */
import AppShell from "@/components/AppShell";
import PageHeading from "@/components/PageHeading";
import { useAtlasTime } from "@/contexts/TimeContext";
import { Clock3, Languages, MoonStar, SunMedium } from "lucide-react";

export default function Settings() {
  const { language, setLanguage, is24Hour, setIs24Hour, lightMode, setLightMode } = useAtlasTime();
  const isAr = language === "ar";
  return <AppShell><div className="content-page settings-page"><PageHeading eyebrow={isAr ? "معايرة شخصية" : "PERSONAL CALIBRATION"} titleAr="الإعدادات" titleEn="Settings" descriptionAr="اضبط القراءة من حولك، واترك هندسة الوقت في مركز الساعة كما هي."/><section className="settings-panel"><div className="setting-row"><span className="setting-icon"><Languages size={18}/></span><div><b>{isAr ? "لغة الواجهة" : "Interface language"}</b><p>{isAr ? "تتغير النصوص والقوائم فقط؛ القرص يبقى صحيحاً بصرياً." : "Only text and navigation change; the dial stays visually true."}</p></div><div className="setting-toggle"><button className={language === "ar" ? "selected" : ""} onClick={() => setLanguage("ar")}>العربية</button><button className={language === "en" ? "selected" : ""} onClick={() => setLanguage("en")}>English</button></div></div><div className="setting-row"><span className="setting-icon"><Clock3 size={18}/></span><div><b>{isAr ? "نظام عرض الوقت" : "Time display"}</b><p>{isAr ? "اختر 12 أو 24 ساعة؛ تظل المنطقة الزمنية مستندة إلى IANA." : "Choose 12 or 24 hour display; timezone stays IANA-based."}</p></div><div className="setting-toggle"><button className={!is24Hour ? "selected" : ""} onClick={() => setIs24Hour(false)}>12h</button><button className={is24Hour ? "selected" : ""} onClick={() => setIs24Hour(true)}>24h</button></div></div><div className="setting-row"><span className="setting-icon">{lightMode ? <SunMedium size={18}/> : <MoonStar size={18}/>}</span><div><b>{isAr ? "المشهد البصري" : "Visual scene"}</b><p>{isAr ? "سمة داكنة افتراضية للأطلس، مع بديل نهاري منخفض التباين." : "The dark atlas is default; a low-contrast daytime alternative is available."}</p></div><div className="setting-toggle"><button className={!lightMode ? "selected" : ""} onClick={() => setLightMode(false)}>{isAr ? "داكن" : "Dark"}</button><button className={lightMode ? "selected" : ""} onClick={() => setLightMode(true)}>{isAr ? "فاتح" : "Light"}</button></div></div></section><p className="settings-footnote">{isAr ? "تُحفظ هذه الخيارات على هذا الجهاز. مزامنة الحسابات جزء من المرحلة التالية للمنصة." : "These choices are saved on this device. Account synchronisation belongs to the next platform phase."}</p></div></AppShell>;
}

